apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: echo
  labels:
    app.kubernetes.io/name: echo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
