apiVersion: batch/v1
kind: Job
metadata:
  name: time-limit-job
  labels:
    app.kubernetes.io/name: time-limit-job
spec:
  parallelism: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: time-limit-job
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: group
                operator: In
                values:
                - minikube
      containers:
      - name: job
        iamge: ghcr.io/gihyodocker/time-limit-job:v0.1.0
        env:
          - name: EXECTION_SECONDS
            value: "60"
      restartPolicy: Never