apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- statefulset.yaml
- service.yaml
secretGenerator:
- files:
  - root_password=./mysql_root_password
  - user_password=./mysql_user_password
  name: mysql
  type: Opaque
commonLabels:
  app.kubernetes.io/component: mysql
