apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  template:
    spec:
      teminateGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: ghcr.io/gihyodocker/taskapp-mysql:v1.0.0
        env:
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: /var/run/secrets/mysql/root_password
        - name: MYSQL_DATABASE
          value: taskapp
        - name: MYSQL_USER
          value: taskapp_user 
        - name: MYSQL_PASSWORD_FILE
          value: /var/run/secrets/mysql/user_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql
          mountPath: "/var/run/secrets/mysql" 
          readOnly: true
      volumes:
        - name: mysql-secret 
          secret:
            secretName: mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
