grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.k3s.local
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.k3s.local
  annotations:
    cert-manager.io/cluster-issuer: k3s-local-ca-issuer
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    storageSpec: {}

alertmanager:
  enabled: false
