apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  cpntainers:
  - name: nginx
    image: nginx:1.25.3
    imagePullPolicy: IfnotPresent
  tolerations:
  - key: "disktype"
    value: "ssd"
    operator: "Equal"
    effect: "NoSchedule"
