---
apiVersion: v1
kind: Service
metadata:
  name: hello-server-external
spec:
  type: NodePort
  selector:
    app: hello-serve
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30599
