apiVersion: v1
kind: Pod
metadata:
  name: deployment-reader
  labels:
    app: deployment-reader
spec:
  serviceAccountName: pod-reader
  containers:
  - name: kubectl
    image: bitnami/kubectl:1.27.4
    command:
    - sh
    - -c
    - |
      while true
      do
        echo "Checking pod..."
        kubectl get deployment --all-namespaces
        sleep 30
      done
