apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: load-test
  labels:
    app.kubernetes.io/name: locust-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: locust-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: locust-worker
    spec:
      containers:
        - name: locust
          image: locustio/locust:2.16.1
          args:
            - --worker
            - "--masteer-host=locust-master"
            - "-H"
            - "http://echo"
            - "-f"
            - "/usr/share/locust/locustfile.py"
          volumeMounts:
            - name: locust
              mountPath: "/usr/share/locust"
              readOnly: true
      volumes:
        - name: locust
          configMap:
            name: locust