[prometheus]
prometheus_server ansible_host=192.168.215.3 ansible_port=22

[grafana]
grafana_server ansible_host=192.168.215.4 ansible_port=22

[nodeexporter]
nodeexporter_server ansible_host=192.168.215.2 ansible_port=22
