apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: nginx
        env:
        - name: BACKEND_MAX_FAILS
          value: "5"