apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-version-blue
  labels:
    app: print-version
    color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print-version
      color: blue
  template:
    metadata:
      labels:
        app: print-version
        color: blue
    spec:
      containers:
      - name: print-version
        image: ghcr.io/gihyodocker/print-version:v0.0.1
        ports:
        - containerPort: 8080
