apiVersion: v1
kind: Service
metadata:
  name: print-version
  labels:
    app: print-version	
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: print-version
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-version
  labels:
    app: print-version
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print-version
  template:
    metadata:
      labels:
        app: print-version
    spec:
      containers:
      - name: print-version
        image: ghcr.io/gihyodocker/print-version:v0.0.1
        ports:
        - containerPort: 8080

