apiVersion: v1
kind: Pod
metadata:
  name: update-checker
  labels:
    app: update-checker
spec:
  containers:
  - name: kubectl
    image: ghcr.io/gihyodocker/debug:v0.1.0
    command:
    - sh
    - -c
    - |
      while true
      do
        VERSION=`curl -s http://print-version`
        echo "[`date`] $VERSION"
        sleep 1
      done
