[ubuntu_linux]
alfa    ansible_host=127.0.0.1 ansible_port=2221
bravo   ansible_host=127.0.0.1 ansible_port=2222
charlie ansible_host=127.0.0.1 ansible_port=2223

[linux_servers:children]
ubuntu_linux
